name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test
        continue-on-error: true
        run: |
          npm install
          gulp test 2> output.txt
          status=$?
          echo ::set-output name=errors::`cat output.txt`
          exit $status
          
      - name: Display Errors
        run: |
          echo ${{ steps.Test.outputs.errors }}